version: '3.9'

services:
  cosmos-db:
    build: /docker/cosmos-db/.
    container_name: cosmos-db
    tty: true
    ports:
      - "8081:8081"
      - "10250-10255:10250-10255"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 3gb
        reservations:
          cpus: '1.5'
          memory: 2gb
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=$ipaddr
  gymmer-api:
    build: /docker/api/.
    container_name: gymmer-api
    tty: true
    entrypoint:
      - /bin/bash
      - -c
      - |
        dotnet restore
        dotnet watch run --project Gymmer.Service
    working_dir: /gymmer-api
    volumes:
       - ~/.aspnet/https:/https:ro
       - ~/repos/GymmerApi:/gymmer-api
    dns:
       - 1.1.1.1
    ports:
      - "5192:5192"
      - "7192:7192"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7192;http://+:5192
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=TestPassword
        