version: '3.9'

services:
  gymmer-api:
    build: .
    image: gymmer-api:latest
    container_name: gymmer-api
    tty: true
    entrypoint:
      - /bin/bash
      - -c
      - |
        dotnet restore
        dotnet watch run --project Gymmer.Service
    working_dir: /gymmer-api
    volumes:
       - ~/.aspnet/https:/https:ro
       - D:/repos/GymmerApi:/gymmer-api
    dns:
       - 1.1.1.1
    ports:
      - "5192:5192"
      - "7192:7192"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7192;http://+:5192
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=TestPassword
        