// <auto-generated />
using System;
using Gymmer.Infrastructure.Persistence.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gymmer.Infrastructure.Persistence.SqliteMigrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20221227100629_TrainingExercises")]
    partial class TrainingExercises
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("Gymmer.Infrastructure.Persistence.Models.ExerciseOptionModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EditionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExerciseOption", (string)null);
                });

            modelBuilder.Entity("Gymmer.Infrastructure.Persistence.Models.TrainingDefinitionExerciseOptionModel", b =>
                {
                    b.Property<long>("TrainingDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExerciseOptionId")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrainingDefinitionId", "ExerciseOptionId");

                    b.HasIndex("ExerciseOptionId");

                    b.ToTable("TrainingDefinitionExerciseOption", (string)null);
                });

            modelBuilder.Entity("Gymmer.Infrastructure.Persistence.Models.TrainingDefinitionModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EditionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TrainingDefinition", (string)null);
                });

            modelBuilder.Entity("Gymmer.Infrastructure.Persistence.Models.TrainingDefinitionExerciseOptionModel", b =>
                {
                    b.HasOne("Gymmer.Infrastructure.Persistence.Models.ExerciseOptionModel", "ExerciseOption")
                        .WithMany("Exercises")
                        .HasForeignKey("ExerciseOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymmer.Infrastructure.Persistence.Models.TrainingDefinitionModel", "TrainingDefinition")
                        .WithMany("Exercises")
                        .HasForeignKey("TrainingDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseOption");

                    b.Navigation("TrainingDefinition");
                });

            modelBuilder.Entity("Gymmer.Infrastructure.Persistence.Models.ExerciseOptionModel", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("Gymmer.Infrastructure.Persistence.Models.TrainingDefinitionModel", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
